---
oled_enabled: true
oled_rotate: false
oled_fahrenheit: false
fan_enabled: true
web_terminal_enabled: false
pikvm_os_update_output_logs: true
hdmi_edid: |
  00FFFFFFFFFFFF005262888800888888
  1C150103800000780AEE91A3544C9926
  0F505425400001000100010001000100
  010001010101D32C80A070381A403020
  350040442100001E7E1D00A050001940
  3020370080001000001E000000FC0050
  492D4B564D20566964656F0A000000FD
  00323D0F2E0F000000000000000001C4
  02030400DE0D20A03058122030203400
  F0B400000018E01500A0400016303020
  3400000000000018B41400A050D01120
  3020350080D810000018AB22A0A05084
  1A3030203600B00E1100001800000000
  00000000000000000000000000000000
  00000000000000000000000000000000
  00000000000000000000000000000045
hdmi_passthrough_enabled: false
validate_variables: true
mouse_jiggler_enabled: true
mouse_jiggler_on_after_reboot: false
mouse_mode: absolute
kvmd_override_enabled: true
serial_over_usb_enabled: true
