---
collections:
  - name: ansible.posix
    version: 1.6.0
  - name: community.crypto
    version: 2.22.0
  - name: community.general
    version: 9.4.0
  - name: community.sops
    version: 1.9.0
  - name: cisco.ios
    version: 9.0.2
  - name: kubernetes.core
    version: 5.0.0
  - name: hifis.toolkit
    version: 4.8.0
  - name: prometheus.prometheus
    version: 0.17.1
roles:
  - name: andrewrothstein.sops
    version: v2.0.1
  - name: buluma.hashicorp
    version: 24.3.31
  - name: buluma.git
    version: 24.3.31
  - name: geerlingguy.ntp
    version: 2.5.0
  - name: lae.proxmox
    version: v1.9.0
  - name: proxmox-test
    src: git+https://github.com/ol3d/ansible-role-proxmox.git
    # version: homelab
    version: feature/vfio-support
  - name: xanmanning.k3s
    version: v3.4.4
  - name: Oefenweb.fail2ban
    version: v4.0.9
  - name: geerlingguy.helm
    version: 1.0.1
  - name: geerlingguy.docker
    version: 7.4.1
  # - name: ceph-ansible.ceph-dashboard
  #   src: https://github.com/ceph/ceph-ansible.git
  #   version: v6.0.28
