---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.crypto
    version: 3.0.5
  - name: community.general
    version: 12.0.1
  - name: community.sops
    version: 2.2.7
  - name: cisco.ios
    version: 11.1.1
  - name: kubernetes.core
    version: 6.2.0
  - name: hifis.toolkit
    version: 6.2.2
  - name: prometheus.prometheus
    version: 0.27.5
roles:
  - name: andrewrothstein.sops
    version: v2.0.8
  - name: buluma.hashicorp
    version: 24.3.31
  - name: buluma.git
    version: 24.3.31
  - name: geerlingguy.ntp
    version: 3.0.0
  - name: lae.proxmox
    version: v1.10.0
  - name: proxmox-test
    src: git+https://github.com/ol3d/ansible-role-proxmox.git
    # version: homelab
    version: feature/vfio-support
  - name: xanmanning.k3s
    version: v3.6.2
  - name: Oefenweb.fail2ban
    version: v4.0.11
  - name: geerlingguy.helm
    version: 1.0.1
  - name: geerlingguy.docker
    version: 7.8.0
  - name: ol3d.pikvm
    version: v1.2.0
  # - name: ceph-ansible.ceph-dashboard
  #   src: https://github.com/ceph/ceph-ansible.git
  #   version: v6.0.28
