kind: Secret
ansible_user: ENC[AES256_GCM,data:hH06OQ==,iv:n0m4UBkX+/40ccJ5Z7wGqXaKYNqvbZhEam8x9jgCqmA=,tag:aS4MPti6IuYPQcl5WGL/jw==,type:str]
ansible_ssh_pass: ENC[AES256_GCM,data:ZMy1yBoVFpe9A+vaxG5l,iv:7s6U5hsQlfivPizP2ojoRRbEujnlw0tPORfSuC6wFVY=,tag:yxJjf8DbR5ainjz/MbXY6g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:DoZ3YpA6cndUnIV/y4kM,iv:lm7pQujvYhBi+Xk7S9GBbRrLVveBlyEILFwCm89Chu0=,tag:28/+FSDAod4rsBhy8xzj0A==,type:str]
pve_ip: ENC[AES256_GCM,data:lK0Ag4E3Jt8tUcQ=,iv:xPvza5Dzg8ENckDnuXE7mNTGLDRZ/oVuSSHJU7qvXJE=,tag:++0ND8nQt9O/WTXueTXzhg==,type:str]
ceph_ip: ENC[AES256_GCM,data:EycKeANGbvFkSFM=,iv:aRWofs5kuIv2TQ9BpJgGunOU9YxZ+zPrH421Ik0TI7k=,tag:FBi103954ZjwVNrK/C24lA==,type:str]
coro_ip: ENC[AES256_GCM,data:/jKncaV8kN5CDCk=,iv:MdjZ7KdDCsN4gugAkge2+Q0Pnf/Q9+f2wKlj85AAe2c=,tag:5VR7as7OvUXP4QvHqAM3Ew==,type:str]
coro_hostname: ENC[AES256_GCM,data:msJBeWdtIw==,iv:wx85Ivk9HmFrbyMbHGzgj8ajP+Kzo9YE6f80k3wXRcY=,tag:oRzO5zBhgdD42UqG7ZEG1Q==,type:str]
osd_id: ENC[AES256_GCM,data:PQ==,iv:97P8drS352oj6zJMbo2MAOHzRNEuUIEHOG9+uxCnou4=,tag:6lCFOidzG1F9lB3Ctw1k9A==,type:int]
coro_iface: ENC[AES256_GCM,data:93nYknaydlY/LeTvyo0a,iv:J4EtiIUojjjAnXjP363z5w6Eoq+UfHOc5TjldKpxgik=,tag:0LhAlL6JYepdRv+Jn/3uNw==,type:str]
ceph_iface_1: ENC[AES256_GCM,data:3E5sYX4Phjvm2PvgSz7B,iv:7DR4xrH5owQBU1r7XCZPdZ4bOGkGdfYU7wrpWHE36K8=,tag:mFE0ssbU8UlHYLk1dPwiSw==,type:str]
ceph_iface_2: ENC[AES256_GCM,data:sKtLWdESEZVZ70ImlEwh,iv:sgWDIsKBnntRFdjmkWH1GoSdf7mwCjYQKj7cIp7/Dtw=,tag:qHFofzgEpzRb4MOVSpCMuQ==,type:str]
hostname: ENC[AES256_GCM,data:U6S6oHUW,iv:6EmkPfNrfR0CxN3DrFTF29LQCcT+w3fvHCsSo0fxZ9I=,tag:Vw+UBtUblvo0WcnlGwuwQQ==,type:str]
root_user: ENC[AES256_GCM,data:0J4l2g==,iv:9Can06qFRl4o547azqNNvc1QSZiirLbqCb6+24wtQhA=,tag:aM74/uYmyIojyNJQM2uYCQ==,type:str]
root_pass: ENC[AES256_GCM,data:UJAKVGxilSHIDSESHgsL,iv:li8QHJnX9x+H5caSUYz06MNpB5mhLUZKe4UV5VMVLWg=,tag:gNQnaGlAXzbrRbxxbWB1FA==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:869935076354:key/4a38975b-065e-4cbc-b0d7-b6067418b38f
      created_at: "2024-10-11T17:12:15Z"
      enc: AQICAHjEXmBmWhTFPoI6sZz9xRf37CwVV0xZ3J51JBykh8WU6gFcLcJIq2IrevKmswH+nL1SAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRbegj30Qj2EvaLv5AgEQgDvTU0exyVBTOCLRDKZ10LjhAh78HdVRrdMmogs8yqy60X8/I2c/jn/XG3AibGqYbgXlJOXID1nNXR4pCQ==
      aws_profile: ""
    - arn: arn:aws:kms:us-east-1:869935076354:key/6baaa7c8-967a-4fc5-9923-c0a938edfcf4
      created_at: "2024-10-11T17:12:15Z"
      enc: AQICAHi4b7+9FI+voNyOntA45UFh2ygAmwOs2iw6TIerHZXspAFDraGGw5GAdZnKQ9/f0T44AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0z4pPk0mykDyJQz3AgEQgDuEpx1uuYv8dHdROhtLhkwOfkgfUyFoh32WvV1IgF1VOevvIpWJYkRMS/cy/r7pZXaH6Lve5fsba/wTGQ==
      aws_profile: ""
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-03-18T20:40:57Z"
  mac: ENC[AES256_GCM,data:Czlbt6xVdByhRLqpNTicdQ0VCRXM6UAS3uzPLFN6MpKkhblbZCSSKY0QdX750LEwyEDqK5ZBectx5RldBRM1GycgmdIhlv0DtGv6wyaEhtcTxnPaS6GhHxfXN1rqXtxEjvSUc2YThd5TylM3LgY29iTO9GEovTwfbJqxX5brnQk=,iv:i5WgX8nko1vKidV7B6KfDnM2iCZDrJ0RO3tW8inhX4E=,tag:rmfxoFMJWgVVtefrcgt08g==,type:str]
  pgp: []
  unencrypted_regex: ^(kind)$
  version: 3.7.3
