kind: Secret
ansible_user: ENC[AES256_GCM,data:OXnOdA==,iv:29JonlNgz4OchfN6Wez8vJh9za1Pg9kFSoO+VMWZ7DE=,tag:VYYzThbDbGXuNKcRunqnug==,type:str]
ansible_ssh_pass: ENC[AES256_GCM,data:6fwgAiI8lDIt49BP7Ze0,iv:Z41+twHs+39l+dhtQfDwsR01T+TA0YmGzTpueyXSurw=,tag:XFzZybbqHSscRPpIxO8T+w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:R5FDfZ/Hx7x1o1vHTi7V,iv:IOuItyoa81I6eKCDgK9DlLvT+Ogv99rZHAdyIYKDSGk=,tag:Bnnw7Ul6XYMSpiwuD1tZzw==,type:str]
hostname: ENC[AES256_GCM,data:+GPmgcswnc/Y5oRl1A==,iv:FcQNAC4Rle4Rt7WR3HvFcHrcAOlnccvs2cNdFsNScCU=,tag:WzhjPc/MDUIFNDvAsMBb9w==,type:str]
k3s_ip: ENC[AES256_GCM,data:y2Nu2zi3bpdBQFE=,iv:9nyIPSQc2nnXyxUPT8WAWGEe/EA6y0aqiXVwIMiK9sE=,tag:ZjdZhKEy0DJjm2WiNxKJgg==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:869935076354:key/4a38975b-065e-4cbc-b0d7-b6067418b38f
      created_at: "2024-10-11T17:12:18Z"
      enc: AQICAHjEXmBmWhTFPoI6sZz9xRf37CwVV0xZ3J51JBykh8WU6gEPpMN+VxvD/uEbOtWLugjOAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrJhAJK2YiTxU3fiUAgEQgDu0mVrAY6AVzMMn5hKtnDd5qL6xgKY7zma5xayARy+mgtPNMsgFitBYPMlquyEHya8DGJX0+xAC0JUBGg==
      aws_profile: ""
    - arn: arn:aws:kms:us-east-1:869935076354:key/6baaa7c8-967a-4fc5-9923-c0a938edfcf4
      created_at: "2024-10-11T17:12:18Z"
      enc: AQICAHi4b7+9FI+voNyOntA45UFh2ygAmwOs2iw6TIerHZXspAG5RJ/aseBPtrXF/U+3NJrhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMLwPhUBcG5Cncg7ouAgEQgDsAUiCSUiWaGg2qvdZ4KGuN6VbDhLUnEX2B0lhL510oIhYq9PHXEaJ7ZgvIvbk/69WFnZWzaVtkrYoEMA==
      aws_profile: ""
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-08-29T00:08:00Z"
  mac: ENC[AES256_GCM,data:7mzuvO28JD1zLRvOhaEgzhF1TRxpO8RVMxmnBpzrS4D5yVr32wRWZ0YjoIV3xd5OJ8MsXGswHnZpNoCip5P+GHdBShjZRMawQRd2cqVK3tB7yR5vYgVjQ57ksFMrAcgQOiQbxf8277VGlErgR0EKM5vjXf3Qs/ewIeHTrwpTznY=,iv:VFzW9VL/dJywlzWsY18IUTldRnLijPtjiwTsXZTRzCs=,tag:ClN8FLHme7UYXD1qzwSAtg==,type:str]
  pgp: []
  unencrypted_regex: ^(kind)$
  version: 3.7.3
